# Generated by cucumber-sinatra. (2014-05-08 12:33:21 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', '/bookmark.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'database_cleaner'

Capybara.app = BookmarkManager

class BookmarkManagerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BookmarkManagerWorld.new
end


# DatabaseCleaner.strategy = :transaction
# DatabaseCleaner.clean_with(:truncation) 
# # do I need both?


# Before do
#   DatabaseCleaner.start  
# end

# After do
#   DatabaseCleaner.clean
# end